### ISSUE TITLE
Error in workflow "org.jeef.emoji". Too many values to unpack. 

### ISSUE THREAD

**Issue by romangaina** [jeeftor/EmojiTaco#10]
Am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/26752061/24473056/aea34022-14d0-11e7-8705-cd73f54b02e5.png)

**Comment by jeeftor** [comment]
No. I'm trying to do work and write a plugin at the same time. :) it's likely my fault. Probe is each time Unicode changes their page I have to update.

**Comment by bhanquier** [comment]
So, any chance of a solution in a foreseeable future?

**Comment by jeeftor** [comment]
Yea there is I just don't have much time right now. Maybe two weeks?

**Comment by bhanquier** [comment]
Will be waiting eagerly ;)
Thanks jeeftor

**Comment by jeeftor** [comment]
The good thing is once you've done the processing you don't ever have to re process.

**Comment by jeeftor** [comment]
Ok - i lied - this was an easy fix:  https://github.com/jeeftor/EmojiTaco/releases/tag/v0.9.48
