### ISSUE TITLE
High CPU usage of workflow update script

### ISSUE THREAD

**Issue by jezdez** [jeeftor/EmojiTaco#11]
After installing and doing the initialization, the workflow would hang in the background and use a high level of CPU until I killed the Python process via the activity manager.

Checking the `/Users/jezdez/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/org.jeef.emoji/org.jeef.emoji.log` file it says at the end:

```
10:27:51 workflow.py:2433 INFO     Checking for update ...
10:27:51 background.py:180 INFO     Task `__workflow_update_check` is already running
10:27:51 workflow.py:2351 DEBUG    Set last run version : 0.9.49
10:27:51 workflow.py:2194 DEBUG    Workflow finished in 0.146 seconds.
14:51:38 background.py:243 ERROR    Command failed with [-9] : [u'/usr/bin/python', '/Users/jezdez/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.72CB48E1-6DF8-430D-B50D-79E2B4410F92/workflow/update.py', u'check', 'jeeftor/EmojiTaco', '0.9.49']
14:51:38 background.py:248 DEBUG    Task `__workflow_update_check` finished
14:51:38 workflow.py:1568 DEBUG    Reading settings from `/Users/jezdez/Library/Application Support/Alfred 3/Workflow Data/org.jeef.emoji/settings.json` ...
14:51:38 workflow.py:2351 DEBUG    Set last run version : 0.9.49
14:51:38 workflow.py:2194 DEBUG    Workflow finished in 16067.089 seconds.
```

14:51 was the time I killed the process. So it seems to have been running for at least 16067.089 seconds, which seems an awful long time for checking for updates ;)

**Comment by miharekar** [comment]
Same here

**Comment by jeeftor** [comment]
Hmmm. I actually noticed this myself recently but I thought it was a proxy issue on my end. I'll look into it

**Comment by garymh** [comment]
Looks like this was related to a certain version of Python. Alfred is now disabling the script in the recent (beta) update:

![screen shot 2017-07-19 at 12 19 37 pm](https://user-images.githubusercontent.com/235202/28380379-b3453ad2-6c7c-11e7-90fe-275b74029656.png)

**Comment by jeeftor** [comment]
Sounds like I better do an update! Expect one by this weekend

**Comment by FrancesCoronel** [comment]
Just wanted to add that yes, the workflow does cause high CPU usage because of the Python script.

![screenshot 2017-07-21 10 39 31](https://user-images.githubusercontent.com/4284691/28475525-7764e36a-6e01-11e7-94c2-7658d01a5959.png)

With the update, it should be ok though!

**Comment by jorgenbs** [comment]
Thanks for the update, had the same issue
