### ISSUE TITLE
What is the latest version?

### ISSUE THREAD

**Issue by ghost** [jeeftor/EmojiTaco#12]
packal.org says it is 0.9.49. But on GitHub it is 0.9.48.

**Comment by jeeftor** [comment]
The latest should be on here in the releases section

**Comment by ghost** [comment]
But how that the link on packal work?

**Comment by jeeftor** [comment]
I have to manually upload a new version to pack all every time i make one and sometimes I forget.

**Comment by ghost** [comment]
So the link on packal is legit?

**Comment by jeeftor** [comment]
If the versions match it's legit. I'm pretty good about updating both at the same time.

**Comment by KMamedoff** [comment]
![screen shot 2017-05-27 at 02 38 34](https://cloud.githubusercontent.com/assets/5307981/26514821/9e972ca6-4285-11e7-88c3-da9e37a12b42.png)
![screen shot 2017-05-27 at 02 38 45](https://cloud.githubusercontent.com/assets/5307981/26514822/a06fa990-4285-11e7-9790-08ca58cc705a.png)
