### ISSUE TITLE
Saving most used emojies

### ISSUE THREAD

**Issue by joshmedeski** [jeeftor/EmojiTaco#13]
I love Alfred because it sorts my items from most used to least.

Is there a way this can be updated to work so when I type `e smiling` it shows the emojis in the order I most use them?

I hope this make sense. It's the same principle for selecting apps in Alfred.

**Comment by jeeftor** [comment]
This isn't a bad idea ... I just dont have time to do stuff alas

**Comment by joshmedeski** [comment]
Totally understand @jeeftor, I've decided to use the built in emoji selector lately on Mac (`cmd+ctrl+space`).
