### ISSUE TITLE
Not finding different skin toned emoji?

### ISSUE THREAD

**Issue by FrancesCoronel** [jeeftor/EmojiTaco#15]
This extension used to work for me but on my new computer, after initializing the emoji, it seems like all the different skin toned emoji are nowhere to be found?

Any thoughts as to why this might be?

<img width="754" alt="screenshot 2018-07-06 11 44 44" src="https://user-images.githubusercontent.com/4284691/42395297-42d0e318-8112-11e8-8d7c-1e9a8ae16668.png">

macOS High Sierra v10.13.5
Emoji Taco v0.9.55
Alfred v3.6.1

**Comment by jeeftor** [comment]
I’m on vacation. When I get back I can give it a look. That being said. Do any of the colors work? It’s possible Mojave supports these new emoji. The data comes from Unicode so if a beta OS X supports a different set than what you are running you won’t have them. 

 https://www.telegraph.co.uk/technology/2017/05/17/redhead-bald-emoji-proposed-2018/

I think this is what is happening. If you run mojave beta you’ll get these guys

**Comment by FrancesCoronel** [comment]
Completely understand, no rush. 

I just saw that in the docs for the workflow, the other different skin toned emoji like 👨🏽were popping up so I thought it was odd it wasn't for me.

I'm not running the macOS beta version right now - just using the latest version of High Sierra.

**Comment by jeeftor** [comment]
You should have some skin tone emoji. Just not all the new ones yet. It’s the cost of being the most up to date emoji plugin :)

**Comment by FrancesCoronel** [comment]
But what if I don't have any different skin toned emoji showing up? 😔😢😞💔🙁😕😪😥☹️😿

**Comment by jeeftor** [comment]
Yea I noticed this today. I think I need to update things cause It wasn’t working after I did a new update.

**Comment by jeeftor** [comment]
I think I can push a new version out tomorrow. Looks like there is a new file I can parse that might make things quicker. 


I parse this file: http://unicode.org/emoji/charts-beta/full-emoji-list.html

Which now appears NOT to have skin tone emoji. 

I think I now need to parse this also: https://unicode.org/emoji/charts-beta/full-emoji-modifiers.html

And we should be good. 

I’ll give it a shot tomorrow

**Comment by FrancesCoronel** [comment]
That makes perfect sense and thank you for the continued support - really appreciate it.

**Comment by jeeftor** [comment]
Try this out:

https://github.com/jeeftor/EmojiTaco/releases/tag/v1.0.2

And let me know if it works.

**Comment by FrancesCoronel** [comment]
It works great now - thank you!! 😊

![screenshot 2018-07-13 17 35 29](https://user-images.githubusercontent.com/4284691/42718927-3b4099de-86c3-11e8-9cf1-12ac12425969.png)
