### ISSUE TITLE
Add Donation Options

### ISSUE THREAD

**Issue by FrancesCoronel** [jeeftor/EmojiTaco#16]
I would love to donate a few dollars towards the work you're doing in your free time for this extremely useful Alfred workflow.

Perhaps you could a section in your README with links to one of the following: your Patreon, PayPal Me, Venmo, Buy Me A Coffee, Open Collective profile, etc..

> quick example:

[![Donate via PayPal](https://img.shields.io/badge/Donate-PayPal-blue.svg?style=flat-square)](http://paypal.me/fvcproductions) [![Become a Patron!](https://img.shields.io/badge/Patreon-Become%20a%20Patron!-orange.svg?style=flat-square)](https://www.patreon.com/fvcproductions)

```markdown
[![Donate via PayPal](https://img.shields.io/badge/Donate-PayPal-blue.svg?style=flat-square)](http://paypal.me/fvcproductions)

[![Become a Patron!](https://img.shields.io/badge/Patreon-Become%20a%20Patron!-orange.svg?style=flat-square)](https://www.patreon.com/fvcproductions)
```

**Comment by godbout** [comment]
+1. crazy awesome and very useful workflow. ready to donate!
