### ISSUE TITLE
Emoji preview icons are not displaying - Big Sur 11.4

### ISSUE THREAD

**Issue by berters** [jeeftor/EmojiTaco#23]
@jeeftor @arthurhammer 
When installing EmojiTaco on BigSur I found that running **init emoji** would actually break the workflow, resulting in:
![image](https://user-images.githubusercontent.com/4118664/124577797-832ff500-de45-11eb-90bc-e51416b189e6.png)

Uninstalling and reinstalling without running the init would result in EmojiTaco working, however there are no preview icons:
![image](https://user-images.githubusercontent.com/4118664/124577912-a195f080-de45-11eb-913c-6608cd59afc5.png)

**Comment by jeeftor** [comment]
Do the img files exist in the workflow directory? 

Somebody has reported a similar issue in the past but I could never validate the big

**Comment by berters** [comment]
@jeeftor thanks for the reply! It seems not. But if I run **init emoji** now to try and have them all downloaded, it will then show  "No emoji found" for everything.


![image](https://user-images.githubusercontent.com/4118664/124589897-68b04880-de52-11eb-9ef8-22a5a1bdade9.png)

![image](https://user-images.githubusercontent.com/4118664/124589920-6f3ec000-de52-11eb-924e-d65457143879.png)

**Comment by berters** [comment]
I tried it again anyway. The image folders are the same after. 

<img width="718" alt="Screenshot 2021-07-06 at 12 07 08@2x" src="https://user-images.githubusercontent.com/4118664/124590541-289d9580-de53-11eb-8f24-848221986c81.png">
<img width="712" alt="Screenshot 2021-07-06 at 12 07 15@2x" src="https://user-images.githubusercontent.com/4118664/124590554-2affef80-de53-11eb-8bc4-39c62d52af76.png">
<img width="296" alt="Screenshot 2021-07-06 at 12 07 26@2x" src="https://user-images.githubusercontent.com/4118664/124590563-2d624980-de53-11eb-83e9-e74cdb1e6acd.png">
<img width="367" alt="Screenshot 2021-07-06 at 12 07 42@2x" src="https://user-images.githubusercontent.com/4118664/124590572-305d3a00-de53-11eb-9c27-67eb16d1375b.png">
![image](https://user-images.githubusercontent.com/4118664/124591024-b5e0ea00-de53-11eb-8029-27e304141de0.png)

---

I uninstalled and reinstalled, and without using **init emoji** it does actually work right away, just without the images:

![image](https://user-images.githubusercontent.com/4118664/124590963-a661a100-de53-11eb-922b-23864bd30200.png)

**Comment by vangquan** [comment]
Same problem to me
macOS 11.5.2
EmojiTaco 1.0.14
Alfred 4.5.1

**Comment by jeeftor** [comment]
Problem duplicated on my end...

**Comment by jeeftor** [comment]
https://github.com/jeeftor/EmojiTaco/releases/download/v1.2.3/Emoji_Taco-1.2.3.alfredworkflow

**Comment by DesertRec** [comment]
Sadly i'm having this issue with no preview emoji both with Version 2.0.1 and 2.0.2.

macOS 12.4, init emoji don't do anything.

<img width="828" alt="Screenshot 2022-05-23 at 06 34 53" src="https://user-images.githubusercontent.com/15858702/169825863-f451e7b1-f820-4e87-82cb-e668abeefa65.png">

**Comment by jeeftor** [comment]
You have python 3?

**Comment by DesertRec** [comment]
Yes only, I have the new Mac Studio which came with macOS 12.3

**Comment by jeeftor** [comment]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/6491743/169908785-7b2a3ff2-055a-499a-99f1-84df81804a4a.png">

Can you guys give me the log ... OH WOW! :)

Nevermind I may have found it:

```
15:28:41 downloadDataFiles.py:125 INFO     Emoji Init Started
15:28:41 bg_downloader.py:24 INFO     Starting BG Task
15:28:41 bg_downloader.py:69 INFO     Downloading http://unicode.org/emoji/charts-beta/full-emoji-list.html
15:28:42 downloadDataFiles.py:125 INFO     Emoji Init Started
15:28:42 workflow.py:2111 ERROR    HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/Users/jstein/devel/emoji/src/libs/workflow/workflow.py", line 2104, in run
    func(self)
  File "/Users/jstein/devel/emoji/src/bg_downloader.py", line 36, in main
    download_file(url, file_name)
  File "/Users/jstein/devel/emoji/src/bg_downloader.py", line 73, in download_file
    remote_file = urlopen(file_url)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
15:28:42 background.py:285 ERROR    [emoji_init] command failed with status 1
```

Looks like they changed their website:

http://unicode.org/emoji/charts-beta/full-emoji-list.html

doesn't seem to work any longer - this should prob be an easy easy fix ... 

(Whomever wrote this software is obviously a terrible programmer)

**Comment by jeeftor** [comment]
Ok looks like Version 15 came out and they changed the website:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/6491743/169909144-71b4f5f6-f3cb-492b-89d6-d679c9b91481.png">

**Comment by jeeftor** [comment]
I don't expect to be able to get to this today -> but in summary:

* This plugin is awesome because it pulls the latest data from Unicode.org
* This plugin is terrible because it relies on Unicode.org to never modify their website :)

Should be an easy fix - I'll keep ya'll updated

**Comment by jeeftor** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/6491743/169909864-81adb3cd-4bac-4a85-a8ed-e0e2d55584db.png">

Here is the link to the emoji chart's i've been parsing - if they've drastically changed the website I'll have to make some additional mods to the code

**Comment by pcherna** [comment]
2.0.1 gives me the same problems (no matches, and no previews in the list). Updating to 2.0.2 fixes the matches, so the core feature now works. I have to re-run "init emoji" in order to get the previews to work, but now everything does.
