### ISSUE TITLE
No longer works OOB on macOS 12.3

### ISSUE THREAD

**Issue by querkmachine** [jeeftor/EmojiTaco#27]
Emoji Taco v1.2.3 — macOS 12.3 beta. 

I've just updated to the macOS 12.3 beta that dropped a couple of days ago (I live dangerously) and Emoji Taco no longer works. No errors or glitches, anything after the initial Alfred keywords (aka, involves running a python script) just doesn't work. 

My assumption is that this is because [macOS 12.3 removes the bundled version of Python 2](https://www.macrumors.com/2022/01/28/apple-removing-python-2-in-macos-12-3/) (something Apple apparently said they were going to do in 2019). Bit weird of them to do that in a minor release, but that's Apple for ya. 

Just giving a head's up in case no one has pointed this out yet!

**Comment by jeeftor** [comment]
We’ll that could def be the problem!!! It’s on my todo list to look at this. There is just so much other stuff going on. Maybe I can take a look this evening

**Comment by jeeftor** [comment]
So I'm on `12.1`

<img width="509" alt="image" src="https://user-images.githubusercontent.com/6491743/151880245-7f2c1c63-54d6-48a3-bd67-a56bb0dbb447.png">


What do you have for `python --version` ?

**Comment by jeeftor** [comment]
I'm assuming 2 possible things:

* Alfred needs an update cause Python is getting messed up
* I need to make the code Python3 compatible (which should be pretty easy to do)

**Comment by jeeftor** [comment]
So obviously Python3 isn't playing nice yet with the "stuff" ... 

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/6491743/151880589-632b3053-4a27-472d-bd10-0824fc683e5a.png">

**Comment by querkmachine** [comment]
Running `python --version` returns "command not found", which seems consistent with it having been removed. 

I do have Python 3 installed (`python3 --version` returns 3.8.9), though my understanding (as per the article linked in the initial issue) is that this is only going to be true for people with Xcode installed, and it isn't enabled otherwise.

**Comment by jeeftor** [comment]
So you are saying that out of the box the latest beta doesn't have any python? Or only has python3? I mean that's going to be a huger Alfred issue all together...

**Comment by jeeftor** [comment]
So I'm using this library: https://github.com/deanishe/alfred-workflow which hasn't been updated to Python3.... but I'm still confused about the beta osx situation with which python is available

**Comment by LampPrinter** [comment]
Not sure if this would help. But have a look.
https://github.com/NorthIsUp/alfred-workflow-py3

**Comment by ilikepeaches** [comment]
Please see https://www.alfredapp.com/help/kb/python-2-monterey/

Installing python 2 via these instructions still results in "python: command not found" errors in the debugging console for the workflow.

Changing "python" in the three script filters to "/usr/local/bin/python" (i.e. to hardcode the newly Homebrew-installed python 2.7 binary) gives this set of errors:

```
[00:36:12.287] ERROR: Emoji Taco[Script Filter] Code 1: .
00:36:12 workflow.py:2055 DEBUG    ---------- Emoji Taco (1.2.3) ----------
00:36:12 workflow.py:1663 DEBUG    saved data: /Users/ilikepeaches/Library/Application Support/Alfred/Workflow Data/org.jeef.emoji/download_percent.cpickle
00:36:12 workflow.py:1663 DEBUG    saved data: /Users/ilikepeaches/Library/Application Support/Alfred/Workflow Data/org.jeef.emoji/phase.cpickle
00:36:12 workflow.py:1663 DEBUG    saved data: /Users/ilikepeaches/Library/Application Support/Alfred/Workflow Data/org.jeef.emoji/emoji_count.cpickle
00:36:12 background.py:233 DEBUG    [bg] command cached: /Users/ilikepeaches/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/org.jeef.emoji/bg.argcache
00:36:12 background.py:237 DEBUG    [bg] passing job to background runner: [u'/usr/bin/python', '/Users/ilikepeaches/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DC274ADB-8DD2-4A6E-B666-01417B55E331/src/workflow/background.pyc', 'bg']
00:36:12 workflow.py:2074 ERROR    [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/ilikepeaches/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DC274ADB-8DD2-4A6E-B666-01417B55E331/src/workflow/workflow.py", line 2067, in run
    func(self)
  File "src/downloadDataFiles.py", line 83, in main
    run_in_background('bg', ['/usr/bin/python', wf.workflowfile('src/bg_downloader.py')])
  File "/Users/ilikepeaches/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DC274ADB-8DD2-4A6E-B666-01417B55E331/src/workflow/background.py", line 238, in run_in_background
    retcode = subprocess.call(cmd)
  File "/Users/ilikepeaches/.pyenv/versions/2.7.18/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/ilikepeaches/.pyenv/versions/2.7.18/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Users/ilikepeaches/.pyenv/versions/2.7.18/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by jeeftor** [comment]
Looks like the background download script is still calling `/usr/bin/python` ... I'm just a bunch of versions behind on the Mac .... hopefully the next version of Alfred will come out soon. I'll look into this but it could be the underlying lib I'm using that is providing python stuff. I tried the py3 upgrade on it and it didn't go as planned....

**Comment by ilikepeaches** [comment]
I got it mostly working by

1. Installing python 2.7 per these instructions: https://www.alfredapp.com/help/kb/python-2-monterey/
2. Changing "python" in the three script filters to "/usr/local/bin/python"
3. Performing a search-and-replace of all files in the workflow bundle: search for all instances of "/usr/bin/python" and replace with "/usr/local/bin/python"

Init Emoji says that it parses 2,243 emoji, and many searches work as expected:

<img width="575" alt="Screen Shot 2022-02-08 at 6 48 54 PM" src="https://user-images.githubusercontent.com/44431584/153095104-8977dfcf-60f1-434b-9a8f-8d9f57cb78a2.png">

but there are some obvious ones now missing?

<img width="575" alt="Screen Shot 2022-02-08 at 6 46 08 PM" src="https://user-images.githubusercontent.com/44431584/153094771-42710905-6600-45ea-8d14-e926a6b85ce2.png">

Hmm.

I don't see anything in the debug output that stands out.

**Comment by ilikepeaches** [comment]
Ah.  I see that the no-peach issue is a separate one: https://github.com/jeeftor/EmojiTaco/issues/24

**Comment by vitorgalvao** [comment]
@jeeftor Go into your three script filters and make the first line:

```bash
export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"
```

That won’t make a difference to anyone using the Workflow now, and for people who are on Monterey 12.3 *and* followed [the knowledge base article](https://www.alfredapp.com/help/kb/python-2-monterey/), it will work as well.

**Comment by ilikepeaches** [comment]
Unfortunately, that updated PATH won't fix the workflow by itself because several hardcoded references to /usr/bin/python remain:

<img width="903" alt="Screen Shot 2022-02-09 at 11 41 37 AM" src="https://user-images.githubusercontent.com/44431584/153247798-65a71008-8d57-47c0-a718-6dd67d19d2f9.png">

@jeeftor if you add the PATH to the script filters per @vitorgalvao *and* change each of those seven '/usr/bin/python' instances to just 'python' (you don't want to hardcode e.g. /usr/local/bin/python because Homebrew only installs in that location on Intel; on M1 the binary will be at /opt/homebrew/bin/python), then the script works, https://github.com/jeeftor/EmojiTaco/issues/24 notwithstanding.

**Comment by godbout** [comment]
just installed 12.3. sacrebleu. missing my tacos emojis.

edit: this was supposed to contain the frown emoji but hey.
edit2: many stuff on my machine are broken now and i fork and update them myself to Python3 but this one is :grimace:

**Comment by jeeftor** [comment]
Sorry guys -> I've been way behind working on other projects... :(

And my version keeps working and working... (so its hard to debug this
stuff)

**Comment by vitorgalvao** [comment]
> And my version keeps working and working... (so its hard to debug this
stuff)

There’s nothing to debug; it’s not a problem with your code but with the tooling it relies on. The Workflow will break for everyone on 12.3—including you—because the Python runtime is no longer present. For the Workflow to keep working you’ll have to either do the changes I and @ilikepeaches pointed out above ([like so](https://transfer.sh/T3OsDh/Emoji%20Taco.alfredworkflow)[^1]) and [instruct people to install Python2](https://www.alfredapp.com/help/kb/python-2-monterey/) or port the Workflow to Python3 (or another language).

[^1]: Untested, but should work. It’s a temporary host because the Workflow is massive and GitHub complains about it.

**Comment by godbout** [comment]
> Sorry guys -> I've been way behind working on other projects... :( And my version keeps working and working... (so its hard to debug this stuff)
> […](#)

no worries man. if i get a bit better at Python i'll have a look. thanks again for the tacos!

**Comment by jeeftor** [comment]
I just ordered a new Mac today (6-8 weeks) -> so I'll likely **have** to fix this automation when it arrives...

So at least thats on the horizon. So I promise it will eventually get done as soon as it stops working for me

**Comment by jeeftor** [comment]
I lied ... i'm working on the code a bit today - but no promises

**Comment by jeeftor** [comment]
Probably wont be done today but i've got a py3 branch that i'm working on locally (outside of alfred) with only `python3` so I've been porting thigs over. Decided to do a big code cleanup while I'm at it (well medium)...

And running into a few python 2-3 issues :)

**Comment by jeeftor** [comment]
So I have the code now running with python3 **BUT** python3 handles unicode / emojis differently so I need to dig through that. Also making a ton of improvements that probably none of you guys care about like adding more comments and return types (totally for readability not for usefulness)

**Comment by jeeftor** [comment]
https://github.com/jeeftor/EmojiTaco/releases/tag/py3

I haven't really had time to test this so its a crapshoot - but in theory it might kinda work

**Comment by godbout** [comment]
> Also making a ton of improvements that probably none of you guys care about like adding more comments and return types (totally for readability not for usefulness)

are you kidding. clean and tight code is sexy af. 😍

**Comment by jeeftor** [comment]
I realized I forgot to update the script commands Alfred actually calls ... oops

**Comment by jeeftor** [comment]
Need to set pythonpath I think and python3 in the scripts if you are so motivated. I'll try tomorrow

**Comment by jeeftor** [comment]
So if somebody feels like testing stuff - I think your script commands need to look something like this:

SEARCH TASK
```bash
 PYTHONPATH=$(pwd)/src/libs python3 src/esearch.py taco
```

INIT TASK

```bash
# No longer needed probably
# find . -name '*.so' | xargs xattr -d -r com.apple.quarantine
 PYTHONPATH=$(pwd)/src/libs python3 src/downloadDataFiles.py 
```
for your execution script on the search call for example


One caveat which may / may not cause issues:

In the background downloading script I'm calling `/usr/bin/python3` so I'll need some folks to verify thats legit as well.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/6491743/159000522-f347e52d-d428-404b-a1f0-1f07151cb216.png">

**Comment by vitorgalvao** [comment]
> In the background downloading script I'm calling `/usr/bin/python3` so I'll need some folks to verify thats legit as well.

If you’re using an unmodified [`alfred-workflow` Python library](https://github.com/deanishe/alfred-workflow/issues/97), it won’t work. That library only works with Python 2, not 3. See https://github.com/deanishe/alfred-workflow/issues/97 for more information, and some efforts towards porting it.

**Comment by pat-s** [comment]
@jeeftor https://github.com/lukewaite/alfred-gitlab/issues/27 might help. I've also successfully used it to port another workflow of mine to `alfred-workflow` using py3.

**Comment by jeeftor** [comment]
Can somebody try the version I pushed? I have a new system on order which will force the issue on my end :)

**Comment by jeeftor** [comment]
The scripts should by py3 compatible for the most part now I think

**Comment by godbout** [comment]
> Can somebody try the version I pushed? I have a new system on order which will force the issue on my end :)

doesn't work in my case sorry. keep getting `modules not found` (cPickle, reload etc.).
but maybe it's my setting. running Python 3.9.12. also my binary is `python3`, not `python`.

edit: just to precise. i've first tried by replacing python by python3 in the Alfred objects. it didn't work. then i've put back python and i've symlinked python to python3 just in case. but got the same results.

**Comment by jeeftor** [comment]
Ok good to know!

(I really wish I had my new mac so i could test this in a clean environment)

**Comment by godbout** [comment]
wish i could help more but really i'm a turd in python. i'll help testing though (although not sure you can totally trust my reports 😬).

**Comment by jeeftor** [comment]
As soon as my new computer arrives - i probably have this fixed within 2-3
days since it will impact me directly :)

**Comment by godbout** [comment]
any place we can send you some donation to sponsor some coffee or beer or coke (hehe see what i did with the last one?) for your awesome work?

**Comment by jeeftor** [comment]
You can hit me here:

https://www.buymeacoffee.com/jeef

**Comment by godbout** [comment]
done. but i've sent some coins rather than hitting. i don't like violence. (ba dum tss.)

**Comment by pat-s** [comment]
I played around a bit and got basic search working.
However I only get the unicode ascii returned and not the emoji - and the `img`s are not downloaded. Leavings this to you :)
But FWIW there is no python3 error anymore.

As you see I needed to copy and duplicate some files as the paths were not correct and the workflow module was not found.
Just did it very dirty but you might want to clean up for prod :)

https://github.com/pat-s/EmojiTaco/tree/py3

To get it working, you can c/p the repo contents into your alfred workflow folder and it should behave as in the screenshot.

![image](https://user-images.githubusercontent.com/8430564/161598249-19060fed-8849-460f-84ce-7ebabd00cf05.png)

PS: I didn't understand why you would need a new mac for testing this. I think you only need to exchange `python` by `python3` in the alfred script blocks and by this you should be able to make use of py3.

**Comment by jeeftor** [comment]
Good point. Mostly I need the motivation of it doesn’t work to siphon off time. 

Maybe I’ll give it a go later today

**Comment by godbout** [comment]
> PS: I didn't understand why you would need a new mac for testing this. I think you only need to exchange `python` by `python3` in the alfred script blocks and by this you should be able to make use of py3.

extra motivation for when the stuff breaks for yourself 😅

**Comment by jeeftor** [comment]
Ya'll called me out ... I'll try to run with python3 on my local version :)

**Comment by jeeftor** [comment]
Updates ... the `init emoji` command seems messed up :(

**Comment by jeeftor** [comment]
It "appears" I'm running into some issues with the background runner -> so I _may_ have to develop a new way in Python3 to download the data files...

**Comment by pat-s** [comment]
Thanks! This seems to coincide with my findings as the `img/` files were not downloaded. Not sure how complicated a fix would be but I guess you can do it! 🚀

**Comment by jeeftor** [comment]
### Update 1

I think I managed to get the BG script running - however - there is currently no GUI information on it which is pretty annoying

<img width="702" alt="image" src="https://user-images.githubusercontent.com/6491743/161628790-dba61795-bc78-40cb-a63d-bc7e7678a4f4.png">

**Comment by jeeftor** [comment]
## Update 2

Perhaps related to the 1st update - but in Python3 JSON text is displayed differently

<img width="841" alt="image" src="https://user-images.githubusercontent.com/6491743/161630231-3efee214-feaa-4815-9b43-d9572658bc3a.png">

So although these scripts work they might be pissing alfred off

**Comment by jeeftor** [comment]
### Update 3

<img width="578" alt="image" src="https://user-images.githubusercontent.com/6491743/161631758-3ee6afbf-b55f-4f69-be6b-e885b6dc20c0.png">

Looks like there were some bugs in the library update process so I'll probably pull that out for now which means ya'll have to manually update

**Comment by jeeftor** [comment]
I'll push out another test shortly ... its going to be a bit shall we say hacky - but it might work. The main issue is you will have to run `init emoji` and then just wait for many minutes - or manually view some log files to see when it completes...

I dont like that but its potentially where things are at right now 😠

**Comment by jeeftor** [comment]
ugh... looks like my release script also needs updates :(

**Comment by jeeftor** [comment]
https://github.com/jeeftor/EmojiTaco/releases/tag/v1.2.15

Ok I pushed a new release.

Main issue is that `init emoji` gives you ZERO feedback and you have to just assume it will work ...

So run that wait like 5-10 mins and then try to search for emoji and give me some feedback. Won't likely try again to fix stuff until tomorrow...

**Comment by godbout** [comment]
`init emoji` fails :frown:

```
[13:57:15.335] ERROR: Emoji Taco[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CD0D6581-5808-4A7F-AE02-0A490C0AE922%3E7D136522-923D-4ACA-AAE1-14513A3840A1)] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
b'\xaf2\x01\x00'
78511
{
  "items": [
    {
      "title": "Starting background process",
      "subtitle": "",
      "valid": false
    }
  ],
  "variables": {
    "count": 0
  },
  "rerun": 1.5
}
```

**Comment by jeeftor** [comment]
Yea I've been seeing a lot of the same errors -> what I saw on my end, however, was even after that error message it kept actually downloading the emoji in the background...

<img width="841" alt="image" src="https://user-images.githubusercontent.com/6491743/161748052-db5a3728-f6a6-47bb-9cc0-3a01676a740b.png">

And once they were downloaded it started working... do you see the same behavior?

**Comment by jeeftor** [comment]
My suspicion is the way that strings work in Python2 vs Python3 unicode strings are different... I may take a pause on this workflow until I can port my progress bar:


<img width="602" alt="image" src="https://user-images.githubusercontent.com/6491743/161748253-d7cdbd04-156f-47db-8d22-d9df57960487.png">

over to Python3 in which case it might solve some of the issues. Its a MUCH simpler codebase I think 

There are also other issues ... but see if you can search emoji right now...

**Comment by jeeftor** [comment]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/6491743/161759076-6a88e5d1-be02-40fb-b9cd-fb3bee8e8a6c.png">

I got the progress workflow working with Python3 - and I found 

I also see the current version is "stupid" shall we say:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/6491743/161759395-3bb28882-2343-4c16-a8f7-265c815fa15b.png">

is returning:

`\U0001F1E8\U0001F1E6\U0000FE0F`

And now I can no longer spam my Canadian coworkers with Canada flags!! NOOO

**Comment by godbout** [comment]
> Yea I've been seeing a lot of the same errors -> what I saw on my end, however, was even after that error message it kept actually downloading the emoji in the background...
> 
> <img alt="image" width="841" src="https://user-images.githubusercontent.com/6491743/161748052-db5a3728-f6a6-47bb-9cc0-3a01676a740b.png">
> 
> And once they were downloaded it started working... do you see the same behavior?

AH. my bad. apologies. you were right, emojis were downloaded and could be parsed. but like you i can't spam Canadians :e_sweat:

**Comment by jeeftor** [comment]
Getting closer:


<img width="592" alt="image" src="https://user-images.githubusercontent.com/6491743/161796245-5aa45419-0312-4a76-ad2e-3411e98f40d3.png">

**Comment by jeeftor** [comment]
Downloading and processing works -> its just the actual plugin that returns unicode strings and not the actual emoji that needs a patch

**Comment by godbout** [comment]
i'm currently back to using EmojiTaco and it's awesome. even with the unicode string \U0001F600\U0000FE0F 
i'm just asking people to go on google and check the 4th result, then they can see the emoji: https://www.google.com/search?q=%5CU0001F600%5CU0000FE0F

\U0001F44D\U0000FE0F

**Comment by jeeftor** [comment]
I just need some more boring meetings and I can finish this off :)

**Comment by godbout** [comment]
\U0001F64F\U0000FE0F

**Comment by jeeftor** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/6491743/161832357-10fbf884-b43c-4d3c-93c1-9f6712b3bdaa.png">

It should just work ... !!! 😠 

I know I'm just down to some super easy fix ... just can't figure out what it is yet

**Comment by jeeftor** [comment]
🌮️🍖️🥩️

It Works!!  (Expect a new release tonight/tomorrow)

**Comment by jeeftor** [comment]
https://github.com/jeeftor/EmojiTaco/releases/tag/v2.0.0-beta-1

Lemme know what bugs I've added!

**Comment by godbout** [comment]
```
[13:46:17.150] ERROR: Emoji Taco[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CD0D6581-5808-4A7F-AE02-0A490C0AE922%3E157AEB44-CD30-445B-B751-7CEDE94BC8A0)] Code 1: Traceback (most recent call last):
  File "src/esearch.py", line 8, in <module>
    from workflow import Workflow3
ModuleNotFoundError: No module named 'workflow'
```

e frown

**Comment by jeeftor** [comment]
Same error on init and debug?

**Comment by pat-s** [comment]
@jeeftor The workflow folder is missing in https://github.com/jeeftor/EmojiTaco/tree/py3/src. Maybe you just forgot to commit it? :)

**Comment by jeeftor** [comment]
Yea I realized that. It's a symlink which I assumed would be included if I directly exported from Alfred. 

I'm updating the workflow lib at the same time. I'll push an update today

**Comment by godbout** [comment]
> Yea I realized that. It's a symlink which I assumed would be included if I directly exported from Alfred.
> 
> I'm updating the workflow lib at the same time. I'll push an update today

hehe that's a classic one. same thing for me when i develop a workflow.

> Same error on init and debug?

so i guess you know by now but yes. had tested all commands, different modules needed but same error. hadn't check the source tho (busy coding!).

**Comment by jeeftor** [comment]
https://github.com/jeeftor/EmojiTaco/releases/tag/v2.0.1

Please let this be the one! 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/6491743/162001664-482dfd94-e20a-4ad7-b80c-e340c7639aab.png">

**Comment by godbout** [comment]
🙈️

**Comment by godbout** [comment]
aww 😍️

**Comment by godbout** [comment]
ok it didn't work the first time i've launched it. ran `init emoji` and let it download in the foreground. once it finished it went straight to ready, no parsing etc. tried again `init emoji` in the background (coz it worked with v2) and i got the notifications, everything got parsed and i can paste -> 🇨🇦️.

**Comment by godbout** [comment]
thank you! life is good again.

**Comment by pat-s** [comment]
Feedback on v2.0.2

`init emoji` seems to be stuck in a loop (quitted after 5 mins):

![image](https://user-images.githubusercontent.com/8430564/162018687-1636dcad-2c2c-48d4-99f9-3f64d7ce88c3.png)

And I am still missing the preview thumbnails - but the copied emojies work and I can paste them 👍

**Comment by jeeftor** [comment]
Does "trying again" help at all for the init once it times out?
