### ISSUE TITLE
Current Version doesn't work with Unicode Version 15

### ISSUE THREAD

**Issue by jeeftor** [jeeftor/EmojiTaco#29]
I'm currently working on this and it connects with #23 

This plugin works by scraping the data from unicode.org - with the latest version of unicode release (v15) the website format has changed and there will be some minor work to do in order to update the plugin. 

If you are having issues with `init emoji` and its May 2022 - this is the issue you are running into.

<img width="764" alt="image" src="https://user-images.githubusercontent.com/6491743/170033634-d8f32380-a8ab-4622-8106-c96e8262cb75.png">

Previouslly I was scraping from the unicode charts - however versions 15's chart:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/6491743/170033717-9b472eae-2b24-41b8-b980-beb3fb61218c.png">

Doesn't seem to exist.

**Comment by jeeftor** [comment]
I filed a request with Unicode and they said it's coming soon. So - I'll work on a fix to pull v14 charts if 15 don't exist

**Comment by jeeftor** [comment]
Just got a new computer - so I'll make sure everything is working again

**Comment by Expatinobz** [comment]
thank you so much for your time and effort!

**Comment by jeeftor** [comment]
It'll take up to two weeks. Day one without my emoji plug-in sucked .... 

So I'm inspired to fix it soon.

**Comment by jeeftor** [comment]
Well -> just ran it today and it seems to work... can ya'll re-verify if the init downloads the correct files?

**Comment by kelicia** [comment]
- I downloaded v2.0.2. ⬇️
- Had to install command line tools on my newer machine. 🧰️
- Ran emoji init. 💫️
- My keyword didn't work. 🤔️
- I checked that they keyword was correct. It was. ✅️
- I opened Alfred debugger. 🐛️
- Everything, (Keyword and taco) worked after that! 🌮️

Seems like something is triggered when debugger is opened perhaps?
