### ISSUE TITLE
strangely doesn't get the latest emojis? 🤔️

### ISSUE THREAD

**Issue by godbout** [jeeftor/EmojiTaco#32]
for example even if i reset and reinit, i can't get the "salute face" that is available in http://unicode.org/emoji/charts/full-emoji-list.html 🤔️

**Comment by godbout** [comment]
ok after 5 tries it's there lol. so definitely not your problem.

**Comment by jeeftor** [comment]
Yea I just tested it yesterday and it seemed to work :)
