### ISSUE TITLE
No Emoji found 😞

### ISSUE THREAD

**Issue by godbout** [jeeftor/EmojiTaco#6]
Hi!

Lovely workflow. Doesn't seem to work for me though currently. Initialized, waited for everything to be ready, but still getting the "No Emoji found" message.

````
[2017-03-15 23:13:33][STDERR: input.scriptfilter] 23:13:33 workflow.py:2156 DEBUG    Workflow version : 0.9.38
23:13:33 workflow.py:1568 DEBUG    Reading settings from `/Users/guill/Library/Application Support/Alfred 3/Workflow Data/org.jeef.emoji/settings.json` ...
23:13:33 workflow.py:2438 DEBUG    Update check not due
23:13:33 workflow.py:2351 DEBUG    Set last run version : 0.9.38
23:13:33 workflow.py:2194 DEBUG    Workflow finished in 0.022 seconds.

**Comment by jeeftor** [comment]
Are you using the latest? On my phone so can't check now. Each time Unicode changes their format I have to update. I have a ci task that alerts me to problems. So if that's good maybe you need a new version of the software. 

I'll try to check later today or tomorrow when in front of a computer.

**Comment by jeeftor** [comment]
Did you run `init emoji` ?  You do have the latest version

**Comment by jeeftor** [comment]
Well thats some crappy ci.  I got this error locally:

```python
Traceback (most recent call last):
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.A25716EE-8B7C-41D8-BAC0-7E12675980A9/workflow/workflow.py", line 2167, in run
    func(self)
  File "buildDataFiles.py", line 97, in main
    raw_code_string = str(cols[headers[u'Code']].text)
KeyError: u'Code'
11:32:18 workflow.py:2194 DEBUG    Workflow finished in 19.304 seconds.
```

**Comment by godbout** [comment]
Yep, ran. All seems good from there. So probably a new format again? Can't really help, I know nothing from Python :D

Thanks!

<img width="328" alt="notificationtablewindow" src="https://cloud.githubusercontent.com/assets/121373/23956429/9484a996-09d7-11e7-9981-3dc4eb9890a0.png">

**Comment by jeeftor** [comment]
Can you try this release: https://github.com/jeeftor/EmojiTaco/releases/tag/0.9.40

haven't had time to test it and wont until later.

**Comment by godbout** [comment]
Unfortunately same same!

**Comment by jeeftor** [comment]
I expected as much. I'll actually have to look over things closer :)

**Comment by adamdicarlo** [comment]
(Also seeing this problem. emoji.csv -> 0 bytes.)

maybe you could use http://www.unicode.org/Public/emoji/4.0/emoji-test.txt instead of scraping the web page? although I guess it doesn't give you image file paths? :/

**Comment by jeeftor** [comment]
Actually ... we are good :)  I made some fixes https://github.com/jeeftor/EmojiTaco/releases/tag/v0.9.41

This should work i think - because it worked locally

**Comment by adamdicarlo** [comment]
😂️  Works like a charm now! Been looking forward to using this extension, it’s awesome!

**Comment by jeeftor** [comment]
Thanks. Can you close out the issue?  Again I'm on a phone

**Comment by adamdicarlo** [comment]
I don't have the ability to... no Close button here. maybe @godbout can tho!
Also, 🤦️ I forgot  to say: Thanks for the fix!! 🙌🏻️

**Comment by godbout** [comment]
😍️😂️🌮️

Excellent 🤣️
Thanks a lot, this is fantastic. I close the issue!
