### ISSUE TITLE
Cannot get rid of Notification Center item

### ISSUE THREAD

**Issue by ghost** [jeeftor/EmojiTaco#7]
![screen shot 2017-03-24 at 19 43 38](https://cloud.githubusercontent.com/assets/5307981/24301903/3c377cec-10ca-11e7-82e0-0a28b291d767.png)
How do I delete it?

**Comment by jeeftor** [comment]
Uhhhh.... maybe remove the workflow? I didn't even know it showed up In there.

**Comment by ghost** [comment]
I removed the workflows months ago. I installed the newest version and also removed it. It stuck here.

**Comment by hpoul** [comment]
fyi, it seems it comes from the `workflow` module, which installs `Notify.app` into `~/Library/Application Support/Alfred 3/Workflow Data/org.jeef.emoji/` .. but you can simply select the entry in the preferences (as you did) and press <kbd>delete</kbd>?
