### ISSUE TITLE
Getting "No Emoji found" even after repeated `init emoji` runs

### ISSUE THREAD

**Issue by cbowns** [jeeftor/EmojiTaco#8]
At some point last week, I did an `init emoji` run to update my emoji, and Emoji Taco has fallen over since then. It reports "No emoji found" even after a deletion of all the caches and other bits I can find.

I've cleaned:
- `~/Library/Application Support/Alfred 3/Workflow Data/org.jeef.emoji/`
-`~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/org.jeef.emoji/`

Any other spots? Any idea why it's failing? The log at `~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/org.jeef.emoji/org.jeef.emoji.log"` doesn't say much about any sort of parsing failure.

**Comment by jeeftor** [comment]
My auto tests were failing this morning. I made some changes but no release. Let me update and see if anything is better.

**Comment by jeeftor** [comment]
https://github.com/jeeftor/EmojiTaco/releases/tag/v0.9.42

give this a go! (totally might not work at all)

**Comment by romangaina** [comment]
totally doesn't work at all =)

stuck at "Parsing emoji data"

**Comment by jeeftor** [comment]
https://github.com/jeeftor/EmojiTaco/releases/tag/v0.9.45 Woohoo! found the error.  They be changing the emoji page with some frequency it would seem.

**Comment by jeeftor** [comment]
uh oh ... might not work ... :(

**Comment by jeeftor** [comment]
Try this: https://github.com/jeeftor/EmojiTaco/releases/tag/v0.9.48

there was an issue with parsing results that had commas embedded in them.

**Comment by jeeftor** [comment]
https://github.com/jeeftor/EmojiTaco/releases/download/v1.2.3/Emoji_Taco-1.2.3.alfredworkflow

Try this version!
